### ISSUE TITLE
Can you provide a simple working example

### ISSUE THREAD

**Issue by hunar1997** [perbone/luascript#14]
Hello

I compiled Godot with this module and created a sprite with a Lua script attached to it, I just wanted to know if it works, how can I do that?
I put a print statement inside the _ready function that was auto generated, but couldn't see anything printed after running

Thanks :D I'm a beginner

**Comment by perbone** [comment]
Hey there!
Thanks for your interest but I'm afreid for now you'll be disappointed as the features already done cannot do too much for the end user (you!). At the moment I'm still researching the best way to integrate Lua into the engine.
Hope you don't give up on this project!
-- Perbone

**Comment by hunar1997** [comment]
Thank you :D
I really like both Lua and Godot, I'll be waiting for this project. I have one small question though, will it be faster than GDScript?

**Comment by perbone** [comment]
If I do my job right yes, it will be faster than GDScript, based on the fact that Lua is the fastest script language out there. But version 4.0 of the engine is expected to have a lot of improvements all of the place including some speed ups for GDScript so it'll be a good and friendly fight to see who's the winner!

**Comment by hunar1997** [comment]
That's great, I hope you will have enough free time and motivation :D
