### ISSUE TITLE
Compiling for Windows: error looking for <sys/wait.h>

### ISSUE THREAD

**Issue by slowpoke-lizard** [perbone/luascript#15]
Hello,

This compiles without any issues on my Debian (targeting Debian).

I fail to compile it for Windows though: 
  scons -j 6  bits=64 module_luascript_enabled=yes target=release_debug tools=yes platform=windows
  [...]
  modules/luascript/lib/lua/lauxlib.c:267:10: fatal error: sys/wait.h: No such file or directory
  267 | #include <sys/wait.h>

As far as I could learn online, mingw-64 doesn't provide a full posix implementation, and the sys/wait.h requirement apparently cannot be satisfied in that context.
Has anyone been able to build it for Windows?

Thanks!

**Comment by Vivraan** [comment]
Have you tried using MSVC?

**Comment by fgombault** [comment]
I haven't, I suppose MSVC is the correct way to go.

**Comment by perbone** [comment]
My apologies for not giving you any help on this matters. As stated before I have macOS and Linux environments so let's hope our good community can help you.
-- Perbone

**Comment by perbone** [comment]
Hi
Did you solve your problem? May I close this issue?

**Comment by Vivraan** [comment]
The issue could also be solved by conditionally disabling `<sys/wait.h>` on Windows while compiling with mingw.

The OP may have abandoned the issue.

**Comment by perbone** [comment]
I see... gonna try this. Thanks for the replay
