### ISSUE TITLE
Is Godot-luascript compatible with IOS and android?

### ISSUE THREAD

**Issue by MassiveArachnid** [perbone/luascript#17]
I was just wondering I plan to export my game to IOS and android and I know Lua alot better than c# thanks

**Comment by perbone** [comment]
There's no problem with running Lua code on iOS. The only thing that is banned by Apple is executing scripts that were downloaded from the network. All your executable code should be either bundled along with your app or user-created. Android has even less restrictions about the use of embedded scripts.
So yes, Godot Luascript is fully compatible with both iOS and Android!
-- Perbone

**Comment by MassiveArachnid** [comment]
Thanks a bunch!

**Comment by jbromberg** [comment]
Just a clarification on this point, would it be possible to write the scripts on iOS and run them there or does it require an export from a desktop machine?
