### ISSUE TITLE
godot 3 api changed

### ISSUE THREAD

**Issue by nneesshh** [perbone/luascript#2]
class "Warning " no longer exists and namespace "MultiplayerAPI" changed to ScriptInstance now

**Comment by perbone** [comment]
Hi @nneesshh 

I'm sorry but I couldn't quite understand what you mean. To me it seems the build is fine. I'm tracking the Godot 3.1 API changes and nothing was caught in my radar lately.

Could you please be more specific?
Thanks for your help!

-- Perbone

**Comment by nneesshh** [comment]
sorry, @perbone，Maybe i am wrong, I am using godot3.0.6 source code now. I will close it
