### ISSUE TITLE
PluginScript

### ISSUE THREAD

**Issue by ShalokShalom** [perbone/luascript#21]
Hi

Luascript is implemented in Plugin Script, or how do you manage compatibility with the code editor,?

**Comment by perbone** [comment]
LuaScript is a module, and it's compatible based on Godot release version. So the editor compatibility is based on the respective API.

**Comment by ShalokShalom** [comment]
Sorry, I ask only if you use PluginScript to provide editor functionality, like Python does?

**Comment by perbone** [comment]
As I said it uses the module API and the editor functionality comes if it.

**Comment by ShalokShalom** [comment]
Thanks a lot

**Comment by perbone** [comment]
Just to clarify, there is no 'module' API, what I meant is that the implementation uses the facilities of Godot modules and that in terms of API, LuaScript uses the API Script, which is basically composed of three main classes, Script, ScriptLanguage and ScriptInstance.
I hope this helps you understand the code.
-- Perbone
