### ISSUE TITLE
Add examples in the README.md

### ISSUE THREAD

**Issue by didicodethat** [perbone/luascript#24]
I was able to compile the engine with the lua script module but I am not able to test the lua functionality, printing doesn't show up on the console and I don't know if this is my fault for not compiling the engine correctly or if it isn't printing because I'm writing the LUA code incorrectly

**Comment by perbone** [comment]
Hi. LuaScript currently is under have rewriting of its parser so right now it's complete unstable. As soon I finish this thing will start to work again.
