### ISSUE TITLE
Failed to build on Ubuntu 20.04.1 LTS

### ISSUE THREAD

**Issue by ghost** [perbone/luascript#29]
Compilation fails almost immediately with the following error message:
https://pastebin.com/NLdAhmMS

-Ubuntu 20.04.1 LTS
-Godot source cloned from Godot 3.2 repository.
-Compiled using: scons platform=windows tools=no target=release_debug bits=64 -j10 tools=yes module_luascript_enabled=yes

**Comment by perbone** [comment]
So let me see if I understand, you are on Ubuntu trying to compile to Windows, is that right? I'm pretty sure that never gonna work buddy. For this to work you need a lot of tooling and extra configuration and all of that is way off the scope of this project.
-- Perbone

**Comment by perbone** [comment]
One more thing, the readme states clearly that you should first compile Godot without Lua and than add Lua, exactly to avoid this kind of unnecessary noise.
Please follow the instructions and report any inconsistency on that.
-- Perbone

**Comment by ghost** [comment]
Perhaps I'm misunderstanding. I successfully cross-compiled for Windows using Ubuntu last night, then git cloned LuaScript into the modules as instructed, which resulted in the error during compilation. You're saying it's an issue with cross-compilation, specifically?

**Comment by perbone** [comment]
Seems to be. Other than that I don't support Windows at the time been, I only have Linux and macos and people reported me problems building on Windows and it is an open issue. So I can imagine cross compilation to Windows will be worst than building on native Windows os.
