### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by cjmxp** [perbone/luascript#3]
godot\modules\luascript\debug.h(26): fatal error C1083: “os/os.h”: No such file or directory

**Comment by perbone** [comment]
Hi
This is probably a problem in your build process. Do you have Godot building ok without Luascript? 
I'm saying that because the way to include Godot 's headers in the source code is correct as long as I know.

**Comment by perbone** [comment]
I apologize. Turns out there is an error due Godot been in constant change before it gets stable.
The fix is in its way to the repository.
-- Perbone
