### ISSUE TITLE
Compiling for macOS fatal error 'core/ustring.h' file not found

### ISSUE THREAD

**Issue by mendsec** [perbone/luascript#34]
I've successfully compiled Godot from source, but when compiled with luascript I give this error on compiling process:

> [ 37%] Compiling ==> modules/luascript/editor/luascript_syntax_highlighter.cpp
In file included from modules/luascript/editor/luascript_syntax_highlighter.cpp:
20:
modules/luascript/editor/luascript_syntax_highlighter.h:33:29: error: no member
      named 'HighlighterInfo' in 'TextEdit'
          virtual Map<int, TextEdit::HighlighterInfo> _get_line_syntax_hig...
                                   ~~~~~~~~~~^
In file included from modules/luascript/editor/luascript_syntax_highlighter.cpp:
21:
modules/luascript/editor/../constants.h:22:10: fatal error: 'core/ustring.h'
      file not found
#include "core/ustring.h"
               ^~~~~~~~~~~~~~~~
2 errors generated.
scons: *** [modules/luascript/editor/luascript_syntax_highlighter.osx.tools.x86_64.o] Error 1
scons: building terminated because of errors.

**Comment by perbone** [comment]
I managed to compile without errors. Are you in the right branch?
