### ISSUE TITLE
Compatibility with Godot 3.2.x

### ISSUE THREAD

**Issue by fosterdouglas** [perbone/luascript#35]
I was having trouble getting Godot to compile with the latest luascript branch (last updated Mar 22 2021) using: 
- Godot 3.2.3-Stable
- macOS 11.0.1
- Python 3.9.2
- SCons 4.1
- yasm 1.3

Reverting to [Godot 3.2.0-Stable](https://github.com/godotengine/godot/tree/3.2-stable) fixed it. It seems like there are some files removed in 3.2.x that luascript depends on to build properly.  Or maybe I was just missing something.  But I wanted to put up a screenshot of the errors in case its useful to the dev!

<img width="769" alt="Screen Shot 2021-03-29 at 1 32 20 PM" src="https://user-images.githubusercontent.com/7971443/112907504-d2c29000-90a2-11eb-9292-938aceedf251.png">

Thanks for making this tool!

**Comment by perbone** [comment]
Hi! My apologies I haven't been keeping track of all changes made in the 3.x series. Pandemic you know? I'll fix it as soon as possible.  Thanks for reporting the issue!

**Comment by fosterdouglas** [comment]
No rush! I just wanted to make sure it was recorded somewhere, in case others were struggling to get it compiling and wondering why.

**Comment by perbone** [comment]
Working on this

**Comment by perbone** [comment]
Please test again
