### ISSUE TITLE
Moonscript 

### ISSUE THREAD

**Issue by ShalokShalom** [perbone/luascript#38]
Hi Paulo

In case, I like to add Moonscript support, can you guide me?

I am both fine by contributing into this repository and as well doing it in my own.

Is it enough, to somewhat register the keywords, operators and similary, and under the hood runs moonscript constantly and evaluates it to Lua?

**Comment by perbone** [comment]
Hi there! Shabbat shalom!
I am not sure mooscript is that simple to implement. If you target gdnative it my be simple but the way I am doing with Lua it's a lot of work to make it run within the engine.
Make your own repository and with I will keep an eye on the issues and will try to help.
-- Perbone
