### ISSUE TITLE
Not found LuaScript in Create Script window

### ISSUE THREAD

**Issue by mendsec** [perbone/luascript#39]
I've successfully built Godot 3.2.3 from source, import luascript module and built it again with success too. But I don't find the option to create a new script file in Lua.

<img src="https://user-images.githubusercontent.com/12684528/127129377-8aefb9b2-5694-4c50-9a60-20ac29d489b0.png" width="360"><img src="https://user-images.githubusercontent.com/12684528/127129410-858051ee-bcfe-49af-b10e-339b35324570.png" width="360">

**Comment by Poikilos** [comment]
Your images are missing (403 forbidden). Save them if you can see them while logged in, then try pushing edit, remove them, then drag the files to the issue.

**Comment by perbone** [comment]
Did you follow the readme to compile with Lua enabled?

**Comment by mendsec** [comment]
> build Godot again adding to the command line the following options
module_luascript_enabled=yes

Yes. Built with success. But errors persist. I removed compiled binary and compiled it again from zero with the module luascript option added. Same again isn't showing LuaScript on create file script window.
