### ISSUE TITLE
LuaJIT

### ISSUE THREAD

**Issue by nico-abram** [perbone/luascript#4]
Have you considered luajit?

**Comment by perbone** [comment]
For the time been only Lua 5.4. There are a good chunk of Lua code for class support and API bind that I will code using the latest language features from 5.4. After that is done I can have a real idea about the effort to support others Lua forks.

**Comment by nico-abram** [comment]
Why was this closed?

**Comment by MetlHedd** [comment]
https://github.com/perbone/luascript/issues/1#issuecomment-483507499

**Comment by perbone** [comment]
Hi! I decided to support both runtimes PUC Rio Lua 5.4 and LuaJIT. Will be a project settings that will impact syntax dialect and game export.
