### ISSUE TITLE
Error building on Windows 10

### ISSUE THREAD

**Issue by ghost** [perbone/luascript#47]
I'm building Godot with luascript on Windows, with [LLVM-Mingw-w64](https://github.com/mstorsjo/llvm-mingw), using the options `scons use_mingw=yes use_llvm=yes use_lld=yes module_luascript_enabled=yes`, and ANTLR4 has several errors in `CommonToken.h` and `CommonToken.cpp`. Most of the errors are dllimport errors, such as `error: definition of dllimport static field not allowed` and `redeclared without 'dllimport' attribute: previous 'dllimport' ignored`. Hopefully this can help make the module work cross-platform.

**Comment by ghost** [comment]
I'm going to try building with a mingw-w64 sourceforge build too, maybe it'll change the output

**Comment by perbone** [comment]
Hi. Unfortunately I don't have a Windows machine to fix this. Any help is much appreciated. Thks
