### ISSUE TITLE
He can't work

### ISSUE THREAD

**Issue by Ehobits** [perbone/luascript#49]
I completed the compilation and used msbuild on windows, but he will not run any lua scripts:
I applied the following script to "Camera3D" and nothing happened.

[MainCamera.zip](https://github.com/perbone/luascript/files/7717284/MainCamera.zip)

**Comment by perbone** [comment]
At the moment the run of the script is disabled due recent parsing rewrite

**Comment by gregkrsak** [comment]
Wait, so I've spent *all day* trying to get this repo to work, and it's just.... disabled? :worried:

**Comment by Poikilos** [comment]
> At the moment the run of the script is disabled due recent parsing rewrite

@perbone, If you mean that the primary feature of the repo (the entire repo) is nonworking, please post an issue "At the moment the run of the script is disabled due recent parsing rewrite" that will track that.
