### ISSUE TITLE
error: use of undeclared identifier 'wcstombs'

### ISSUE THREAD

**Issue by oBattleTurtleo** [perbone/luascript#5]
Hi perbone, I'm facing this error, what should I do to fix it? thanks.

![Screenshot 2019-04-02 at 1 35 15 PM](https://user-images.githubusercontent.com/41368833/55381040-411ff680-554c-11e9-9fc4-bcd565dc3b17.png)

**Comment by ShoesForClues** [comment]
you can fix this by adding `#include <cstdlib> ` in debug.h

**Comment by oBattleTurtleo** [comment]
Hi, ShoesForClues
it works, thanks.

**Comment by perbone** [comment]
Interestingly, I've never had this kind of error, but, I imagine, this dependency had previously been inherited from Godot's includes. 
So to be safe I included the dependency as suggested.
Fixed and sent to upstream.
Thank's guys.
