### ISSUE TITLE
Error compiling on WSL Ubuntu

### ISSUE THREAD

**Issue by ghost** [perbone/luascript#50]
![image](https://user-images.githubusercontent.com/83098445/147717818-35f1a8b3-d772-4a4b-ac51-1cbe0f0aaa66.png)
I get an error saying that the `sys/wait.h` library does not exist. Is this an error with the library or is it just me? I'm compiling on WSL Ubuntu with Windows 11.

**Comment by perbone** [comment]
Never saw this kind of error. Other than that I don't t support Widows so I can't help you with this. But to me there's some thing strange as you are on Ubuntu but the binary shows Windows tool. 
I'll keep this open for a little to see with some one can give you a hand on this. 
-Perbone

**Comment by ghost** [comment]
Thanks. I'm compiling with `platform=windows` which is why it's showing the tools for Windows, but I don't think that it should effect the compiling.
