### ISSUE TITLE
Which of the features listed are already implemented?

### ISSUE THREAD

**Issue by komerdoor** [perbone/luascript#52]
In your README there is a list of features. Which ones have already been implemented?

**Comment by Poikilos** [comment]
If there was a checklist that would look good when looking at the repo on the web. Markdown:
```
- [x] feature 1
- feature 2
  - [x] feature 2a
  - [ ] feature 2b
```

becomes:
- [x] feature 1
- feature 2
  - [x] feature 2a
  - [ ] feature 2b

**Comment by Poikilos** [comment]
@perbone Uhh, how can I contribute if I don't know what's going on?

Generally, closing an issue comes with an explanation or citing a change.

**Comment by perbone** [comment]
My apologies I was in a rush. 
So at the moment the project is kind of stuck,  I'm just keeping it compiling with Godot master. 
There are two reasons why this is.  First the Godot is in constant changes due the 4.0 series been a big project, lots of things are changing in a weekly basis so it's difficult to keep up with them. Second,  I have my doubts with this project is worth my time.  See the current Script API is too deep into the GDScript way of doing things,  and I'm starting to think that no other script language can be successfully integrated with the engine. 
So at the moment there is no need for contributors to use their time on this project. 
Anyway thanks a lot for your interest. 
- Perbone
