### ISSUE TITLE
Does this project do not use the Lua VM and parser/lexer?

### ISSUE THREAD

**Issue by ex** [perbone/luascript#55]
Hello, I found your project and it looks interesting.
I have made modifications to Lua 5.2 to fit my liking in a language I called Killa.
Long time ago I used it to embed support for my language in Cocos2dx++ and Love2D both game engines with Lua support.
They are now obsolete, and I was planing to use Killa in Godot, not a fan of GDScript to be honest and I prefer C++ for everything performance related. So anyways, I was skimming your repo code and saw the usage of ANTLR and commits about parsing Lua, that I don't understand. Is this used only for the Lua code editor?. I would like to use your project to bootstrap my project of Killa in Godot if possible. Thanks for your time.

**Comment by perbone** [comment]
Hi Laurens
ANTLR is most used for the editor not the runtime. I'm not doing runtime stuff yet so not sure my project can be that useful for you at this moment. I would look to gdextensions if you are most interested in runtime and not so much in the UI/UX editor stuff. If memory servers me someone already wrote a runtime for Lua using gdnative.
- Perbone

**Comment by ex** [comment]
thanks! there is nothing to my liking right now, there was a project that is using LuaJIT that I can't use.
I'll be watching your project in the meantime, I hope you can make the runtime work someday.
Best.
