### ISSUE TITLE
Help, How can i use this

### ISSUE THREAD

**Issue by BlueCatGamess** [perbone/luascript#58]
Hi!
I know here is not the right place for this, but a follow the steps to install this plugin, build godot and i dont how to use this, can you help me plz?

![image](https://user-images.githubusercontent.com/113129303/199591996-e98162b7-df89-475f-9e91-2ee5736c428b.png)

I made this test, but the print dont works.

**Comment by perbone** [comment]
Hi sorry for taking to long. So it is still in development and has little use for gaming right now. The pandemic really slow me down. I'll try to speed things up in the coming months.
