### ISSUE TITLE
Can you share the compiled version, thank you ~!

### ISSUE THREAD

**Issue by xky5000** [perbone/luascript#61]
In winosw system compilation failed, tried a lot of methods are not successful, can share the compiled version? thank you ~!

**Comment by perbone** [comment]
Hi! Sorry for taking so long to answer.
So as I wrote in the read me file unfortunately I don't have a Windows machine and that difficult to build a Windows release. I'm saving to buy a new PC so I hope in the near future I can have a better development environment, including Windows.
