### ISSUE TITLE
Error code when trying to when trying to enable in plugins.

### ISSUE THREAD

**Issue by meatree** [perbone/luascript#66]
Here is the Error code "Unable to load addon script from path: 'res://addons/godot-lua-pluginscript/plugin/plugin.gd'. This might be due to a code error in that script. Disabling the addon at 'res://addons/godot-lua-pluginscript/plugin/plugin.cfg' to prevent further errors."
<img width="471" alt="Capture" src="https://github.com/perbone/luascript/assets/165381475/463c2db1-08a0-4de1-9166-5cb5a955f111">

**Comment by perbone** [comment]
This is not a plugin it's a module. So I don't know what you are doing but cannot help you with this.
