### ISSUE TITLE
can´t compile with lua

### ISSUE THREAD

**Issue by Antonygamergod** [perbone/luascript#68]
everytime i compile "scons platform=windows module_luascript_enabled=yes" using this command it gives an error 

scons: *** Import of non-existent variable ''env_modules''
File "C:\Users\user\Downloads\godot source code(for lua)\modules\SCsub", line 4, in <module>

how do i solve this

**Comment by Antonygamergod** [comment]
this happens in every version i think(i tested v4.3 beta, v4.2.2 stable and 4.0.4 stable)

**Comment by perbone** [comment]
No longer an issue
