### ISSUE TITLE
[Linux Mint 19.1 x86_64] Not compiling with godot 3.1.1 stable

### ISSUE THREAD

**Issue by Teashrock** [perbone/luascript#7]
Refuses to compile with this command line:
`scons -j8 platform=x11 udev=yes tools=yes module_luascript_enabled=yes`
Build Log here:
https://pastebin.com/XzcgW341

**Comment by perbone** [comment]
The current code is based on Godot 3.2-master. There was API changes between Godot 3.1.x and 3.2 and as LuaScript is not yet released I'm keeping in sync only with master. Sorry for the inconvenience.

**Comment by Teashrock** [comment]
I see. Thank you for quick answer. Issue closed.
