### ISSUE TITLE
How to Disable/Capture Lua Logging to Terminal?

### ISSUE THREAD

**Issue by ghost** [perbone/luascript#9]
I have a logger in my game which takes a verbosity value and determines how much data to spit out to the terminal. It also saves to a file if the feature is enabled.

I would like to know if there is a way to turn on/off Lua logging via script and if it is possible to capture the output of the log into a variable? If not, I would also like to add this as a feature request.

Thanks!

**Comment by perbone** [comment]
Hi @alex-evelyn 

Good question! Till now I wasn't thinking the logging should be disabled as the project is in its early development. I guess it is a good feature to have. So in the future will implement this.

Thanks for your interest
